docs/practitioner/carbon-efficiency.md

adding answers for carbon efficiency's quiz

adding answers for carbon efficiency's quiz 

---

docs/practitioner/carbon-awareness.md
docs/practitioner/climate-commitments.md
docs/practitioner/energy-efficiency.md
docs/practitioner/hardware-efficiency.md
docs/practitioner/measurement.md

adding answers to all questions except carbon efficiency section

adding answers to all questions except carbon efficiency section

---

docs/practitioner/hardware-efficiency.md

Addressing issue [8](https://github.com/Green-Software-Foundation/training/issues/8): 
I found the study where the image was taken from. However, the study does not have the exact details to update the missing figures. So I have deleted the paragraph where the figures were and updated the text to link the study.

Addressing issue 8

---

docs/practitioner/energy-efficiency.md

This change addresses [issue 12](https://github.com/Green-Software-Foundation/training/issues/12).

Addressing issue 12

---

docs/practitioner/carbon-awareness.md

fix numbering in Energy markets section

fix numbering

---

README.md
docs/index.mdx
docusaurus.config.js

Attempting to update the website URL from https://training.greensoftware.foundation/ to https://learn.greensoftware.foundation/

attempting to update website url

---

docs/practitioner/climate-commitments.md

This is related to the issue #24

Best ref for abatement

---

docs/practitioner/carbon-efficiency.md

addressing issue [9](https://github.com/Green-Software-Foundation/training/issues/9)

addressing issue 9

---

docs/practitioner/measurement.md

addressing issue [38](https://github.com/Green-Software-Foundation/training/issues/38)

addressing issue 38

---

docs/practitioner/introduction.md

Address issue [36](https://github.com/Green-Software-Foundation/training/issues/36): update the introduction to match what's written in the section

addressing issue 36

---

docs/practitioner/climate-commitments.md

addressing issue [31](https://github.com/Green-Software-Foundation/training/issues/31)

addressing issue 31

---

docs/practitioner/climate-commitments.md

addressing issue [32](https://github.com/Green-Software-Foundation/training/issues/32)

addressing issue 32

---

docs/practitioner/carbon-efficiency.md

Addressing issue [37](https://github.com/Green-Software-Foundation/training/issues/37): quizzes numbering

Addressing issue 37

---

docs/practitioner/carbon-efficiency.md
docs/practitioner/glossery.md

addressing issues [35](https://github.com/Green-Software-Foundation/training/issues/35) and [15](https://github.com/Green-Software-Foundation/training/issues/15): we are changing gasses to gases

addressing issue 35 and 15 

---

docs/practitioner/climate-commitments.md

addressing issue [25](https://github.com/Green-Software-Foundation/training/issues/25)

addressing issue 25

---

docs/practitioner/climate-commitments.md

addressing issue [28](https://github.com/Green-Software-Foundation/training/issues/28)

addressing issue 28

---

docs/practitioner/climate-commitments.md

addressing issue [33](https://github.com/Green-Software-Foundation/training/issues/33)

addressing issue 33

---

docs/index.mdx

fix typo in index.mdx

---

docs/practitioner/introduction.md

Fixed US spelling issue - catalog

Update triangle image

---

docs/practitioner/introduction.md

linking pattern's website in intro section

linking pattern's website in intro section

---

docs/practitioner/hardware-efficiency.mdx

addressing issue [78](https://github.com/Green-Software-Foundation/training/issues/78)

addressing issue 78

---

docs/practitioner/climate-commitments.mdx

Addressing issue [79](https://github.com/Green-Software-Foundation/training/issues/79)

addressing issue 79

---

docs/practitioner/carbon-efficiency.mdx

Addressing issue [77](https://github.com/Green-Software-Foundation/training/issues/77)

Addressing issue 77

---

docs/practitioner/energy-efficiency.mdx

address pr [68](https://github.com/Green-Software-Foundation/training/pull/68): update quiz in energy efficiency

update quiz in energy efficiency

---

docs/practitioner/introduction.md

Addressing issue [36](https://github.com/Green-Software-Foundation/training/issues/36): fix phrasing in the introduction

Addressing issue 36: fix phrasing in introduction

---

docs/practitioner/carbon-awareness.mdx

address typo in carbon awareness

address typo in carbon awareness

---

docs/practitioner/glossery.md

fix a couple of issues for useful terms section

fix a couple of issues for useful terms section

---

docs/practitioner/carbon-efficiency.mdx

addressing issue [77](https://github.com/Green-Software-Foundation/training/issues/77)

changing subscription of CO2

---

docs/practitioner/energy-efficiency.mdx

Addressing issue [71](https://github.com/Green-Software-Foundation/training/issues/71)

adding 2 more questions for energy efficiency

---

docs/practitioner/carbon-awareness.mdx
docs/practitioner/carbon-efficiency.mdx
docs/practitioner/climate-commitments.mdx
docs/practitioner/energy-efficiency.mdx
docs/practitioner/hardware-efficiency.mdx
docs/practitioner/measurement.mdx

@jawache these are all the updates that you suggested in the google document recently
@greenhsu123 please check if I processed them correctly. I'll download the file for you and will share via email.

Final review of the quiz (Q&A)

---

docusaurus.config.js

Small PR to fix #106 
Please let me know if you prefer that I create the PR against a different branch.

fix:  edit link points to wrong Github repository.

---

docs/energy-efficiency.mdx

Update content and question related to energy measurement in line with https://github.com/Green-Software-Foundation/training/issues/127

Update energy measurement

---

docs/measurement.mdx

fix typo identified in issue [172](https://github.com/Green-Software-Foundation/learn/issues/172)

fix typo identified in issue 172

---

docs/glossary.md

fixing issue identified in [169](https://github.com/Green-Software-Foundation/learn/issues/169)

fixing issue identified in 169

---

docs/carbon-awareness.mdx

To address the issue [180](https://github.com/Green-Software-Foundation/learn/issues/180), where demand shifting is mentioned instead of demand shaping.

to address issue 180

---

docs/carbon-efficiency.mdx
docs/glossary.md

addressing issues raised through the Linux Foundation Forum - https://github.com/Green-Software-Foundation/learn/discussions/183

addressing issue raised through Linux Foundation Forum 

---

docs/hardware-efficiency.mdx

Fixing a small typo I noticed. Thanks for a great course!

Fix small typo

---

docs/introduction.md

Content flow error "run and build" should be "build and run"

Update introduction.md - run and build changed to build and run

---

docs/climate-commitments.mdx

Addressing suggestions in https://github.com/Green-Software-Foundation/learn/issues/239

update "electron flow" wording in climate commitment section 
